# -*- coding: utf-8 -*-
"""Copy of Python Strings .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jp19rkiQJ7qU5_h_d3qgwv4D2EGxvFdj

### Question 1: Write a Python program to count the number of characters in a string without using len function.

- `sample input : `
    - `var = 'python java'`
- `sample output :`
    - `result : 11`
"""

# Please write The solution Here for above question 1:

var='python java'

count = 0

for i in var:
  count+=1

print(count)

"""### Question 2: Write a Python program to reverse a string without using [::-1]

- `sample input : `
    - `var = 'python'`
- `sample output :`
    - `result : nohtyp`
"""

# Please write The solution Here for above question 2:

var='python'

reversed_var=''

for i in var:
 reversed_var=i+reversed_var

print(reversed_var)

"""### Question 3: Write a Python program to check if a string is a palindrome don't use [::-1].

- `sample input : `
    - `var = 'NUN'`
- `sample output :`
    - `result : It is a Palindrome`
    
- `palindrome concept = https://www.dictionary.com/e/palindromic-word/#:~:text=A%20palindrome%20is%20a%20word,roots%20in%20the%20early%201600s.`
"""

# Please write The solution Here for above question 3:

var= 'NUN'

str= ""

for i in var:
  str=i+str

if(var==str):
    print("it is a polindram")
else:
    print("it is not a polindram")

"""### Question 4: Write a Python program to find the most common character in a string.

- `sample input : `
    - `var = 'Hello world '`
- `sample output :`
    - `result : l, because l is repeating 3 times `
"""

# Please write The solution Here for above question 4:

#text='Hello World'
#print(text.count('l'))

var='Hello World'

most_common_char=max(set(var),key=var.count)
#print('The most common  character is' ,most_common_char)

print(most_common_char)

"""### Question 5: Write a Python program to check if two strings are anagrams.

- `sample input : `
    - `var1 = 'listen'`
    - `var2 = 'silent'`
- `sample output :`
    - `result : both are anagram because characters in var2 is in var1`
"""

# Please write The solution Here for above question 5:

var1 = "listen"
var2 = "silent"

var1=sorted(var1.lower())
var2=sorted(var2.lower())

if var1==var2:
  print("both are anagrams because characters in var2 is in var1")
else:
    print("both are anagrams because characters in var2 is in var1")

"""### Question 6: Write a Python program to remove all the vowels from a string.

- `sample input : `
    - `var = 'python'`
- `sample output :`
    - `result : pythn , because vowels are [AEIOUaeiou]`
"""

# Please write The solution Here for above question 6:

var = 'python'

vowels = ['a','e','i','o','u']
result = ""

for i in range(len(var)):
  if var[i] not in vowels:
    result = result + var[i]

print(result,", bacause vovels are [AEIOUaeiou]")

"""### Question 7: Write a Python program to find the longest word in a string.

- `sample input : `
    - `var = 'python is Easy Language'`
- `sample output :`
    - `result : Language`
"""

# Please write The solution Here for above question 7:

var = 'python is easy Language'

longest = max(var.split(),key=len)

print("Longest word is:" ,longest)

"""### Question 8: Write a Python program to capitalize the first letter of each word in a string [dont use built-in-function title].

- `sample input : `
    - `var = 'python is easy'`
- `sample output :`
    - `result : Python Is Easy`
"""

# Please write The solution Here for above question 8:

var ='python is easy'

var1=var.split(" ")[0].capitalize()+" "+var.split(" ")[1].capitalize()+" "+var.split(" ")[2].capitalize()

print(var1)

"""### Question 9: Write a Python program to find the frequency of each character in a string.

- `sample input : `
    - `var = 'sharuk khan'`
- `sample output :`
    - `result : {'s': 1, 'h': 2, 'a': 2, 'r': 1, 'u': 1, 'k': 2, ' ': 1, 'n': 1}`
"""

# Please write The solution Here for above question 9:

var = "sharuk khan"

for i in var:
  frequency = var.count(i)
  print(str(i) +": " + str(frequency), end=", ")

"""### Question 10: write a python programme to find the sum of all the even characters based on Ascii values

- `sample input : `
    - `var = 'sharuk khan'`
- `sample output :`
    - `result : 464`

"""



# Please write The solution Here for above question 10:




pass






# saikamal9797@gmail.com

